tydeno/Ploto

- Ploto.psm1
**New features**
- Added -Verbose capability for Invoke-PlotoJobs (-Verbose Switch) fix #3 
- Perfcounter became a SwicthParam
- Added StartTime Property for Get-PlotoJobs (To track progress and estimate endtime)
- Added Aborted state (if no process that matches PID for jobs that are not completed)
- Removed PID from completed Jobs
- CleanUp function
**Bugfixes**
- fixed a bug with Get-PlotoTempDrives: Did not filter for completed jobs. Does now. fix #1 
- fixed a bug with Get-PlotoTempDrives: Wrong calculation of AmountOfPlotsToTempMax if drive has active Jobs. Fixed now.
- fixed a bug that owerspawned in certain situations
> 1.0.4: Detection and CleanUp of aborted Jobs & Bugfixing

- LICENSE
> Adding MIT lic

- Ploto.psm1
> Fixed doublespawn on same disk

- Ploto.psm1
> Beautifying for release

- Ploto.psm1
* CompletionTimes as Output in Get-PlotoJobs closes #17 
* fixes a misleading behaviour that Ploto actually waited too long when it came out of iterating trough drives that have more than 1 plot.
* fixes #18  the issue of ploto only diplaying the last job of a drive, if it has more than one job 
* fixed messy -verbose output from Get-PlotoJobs
> CompletionTimes and bugfixes

- README.md
Add note to delete previously created Logs in order to get Ploto going #21
> Add clearer instructions

- Ploto.psm1
- PlotoAlertConfig.json
- README.md
* configurable Discord Notifications (Discord Webhooks) #29 
* When a jobs is spawned
* When no Outdrives are available
* When a job fails to spawn/
* decreased wait timer from 10 to 4 seconds for Stop-PlotoStop before deleting .tmp files
* several bugs that lead to unexpected spawning behaviour (not complying with params at all in some weird cases)
> Plotify; Get notifications on the go

- Ploto.psm1
Potentially will help with #34
> A potential hotfix for #34

- Ploto.psm1
- PlotoAlertConfig.json
Finally fixed #34
* Start-PlotoFy Function: Starts a Background Job with "Request-PlotoFyStatusReport
* Request-PlotoFyStatusReport: Continously Calls "Invoke-PlotoFyStatusReport" with defined Intervall in config
* Invoke-PlotoFyStatusReport: Gets active and completed jobs and shows them in Discord. Also tells you when there is no job going round
> Final hotfix34 plotofy adds

- Ploto.psm1
- README.md
* Ability to send StatusReports on a intervall you like about completed and jobs in progress
> Plotofy statusreports

- Ploto.psm1
Now throws an error if you have logs in your logs folder that were not created with Ploto. And according information.
> Potential fix for #40

- Ploto.psm1
* ErrorAction to silentlycontinue when jobscount indexes to null (not critical)
> real fix for #40

- Ploto.psm1
- PlotoAlertConfig.json
* We get path to Ploto now from config file
> Changed the way we specify PathToPloto in PlotoFy

- Ploto.psm1
* Ploto now picks the OutDrive with least jobs in progress instead of OutDrive with most free space. closes #56
> Select OutDrive with least jobs

- Ploto.psm1
- PlotoSpawnerConfig.json
* Ability to define max parallel jobs in phase 1 per each disk. closes #4 
* Ability to define max parallel jobs in phase 1 on all disks. #4
* Ability to launch a new plot when a given phase is completed (EarlyStart, set to 3 advised. So when a job completed phase 3, the next can be started). #4
* PlotJob Phase on Get-PlotoDisks (Temp/Out/T2)
* Waaay less noisy verbose. Finally is usable to trace what Ploto is doing.
* Improper Job Count when Alarms enabled. closes #55
* Some bugfixes and refactoring
> More dynamic staggering and some fixes

- Ploto.psm1
* Remove-AbortedJobs/Stop-PlotoJobs now also does clean up of temporary t2 files. closes #63 
* More resilience for Remove-AbortedJobs/Stop-PlotoJobs trough less generalization
* Some more output for console
> t2 tmp file deletion

- Ploto.psm1
Check if "plotter" paths exists. If it does not, it gets created. Helps with first time run of Ploto.
> check if plotter path exists

- Install-Ploto.ps1
- Ploto.psm1
- PlotoSpawnerConfig.json
- README.md
* An Installer script that correctly installs/updates Ploto Module and guides trough the setup of the config.
Also copies config to where it needs to be.
* Ability to launch Ploto commands globally without need to import first (Thanks to installer)
* Replotting capabilities; A watchdog that looks for jobs that are about to enter phase 4 and has IsReplot set to true. Then deletes a plot on defined RepotDrive closes #75 
* Ability to Define ReplotDriveDenom
* A bug that did not set -f param when usin a P2Singleton to plot
> installer and replot

- Install-Ploto.ps1
- Ploto.psm1
- PlotoSpawnerConfig.json
restructured the whole config somewhat
> Config restructure

- Install-Ploto.ps1
- Ploto.psm1
- PlotoSpawnerConfig.json
- README.md
* Support for [madMAx43v3r](https://github.com/madMAx43v3r/chia-plotter) and [stotiks ](https://github.com/stotiks/chia-plotter) blazing fast custom plotter. closes #86
* A few improvements on the installer
* shows selected drives by denom in cfg mode  
* A config handout when Ploto Spawns
* A cleaner config
* Notifications when Remove-AbortedPlotoJObs detects an aborted Job
* Add Size of plotfiles on t2 drive in Get-PlotoJobs 
* Ommits -p  and -f in output of `Get-PlotoJobs` and shows "YourKeys" instead for those params.
* Completed Job is considered "Aborted" closes #90
* When T2 is same as TempDrive error on Remove-AbortedJobs closes #89
* and various more
> Support for madmax/stotik plotters

- Install-Ploto.ps1
* The whole logic how config diff is handled.
When Install-Ploto.ps1 script is run, it checks whether there are any new properties introduced in config (vs. installed cfg).
If so, it shows the missing properties in installed config.
* An issue when Ploto was installed from a release that cmdlet where not recognized globally. closes # 97
> Addedd config diff to get newly added props
